# Generated by Django 3.0.8 on 2020-07-09 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TituloPost', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('descricao_no_buscar', models.TextField(max_length=100)),
                ('preco', models.IntegerField()),
                ('rendimento', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('data_do_post', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
    ]
