# Generated by Django 3.0.8 on 2020-07-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='rendimento',
        ),
    ]
