# Generated by Django 3.0.8 on 2020-07-09 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200709_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TituloPost', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('descricao_no_buscar', models.TextField(max_length=100)),
                ('preco', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('data_do_post', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='AllPosts',
        ),
    ]
