# Generated by Django 3.0.8 on 2020-07-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200709_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpost',
            name='foto_produto',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='allpost',
            name='TituloPost',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='allpost',
            name='descricao_no_buscar',
            field=models.TextField(max_length=150),
        ),
    ]
