# Generated by Django 3.0.8 on 2020-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_allpost_foto_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpost',
            name='foto_produto',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='allpost',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
    ]
