# Generated by Django 3.0.8 on 2020-07-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200719_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpost',
            name='Cinco_Estrela',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='allpost',
            name='Duas_Estrela',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='allpost',
            name='Quatro_Estrela',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='allpost',
            name='Tres_Estrela',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='allpost',
            name='Uma_Estrela',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
