# Generated by Django 3.0.8 on 2020-07-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200719_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpost',
            name='Estrelas',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='allpost',
            name='Votos_Totais',
            field=models.IntegerField(default=0, max_length=5000),
        ),
    ]
