# Generated by Django 3.0.8 on 2020-07-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200719_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpost',
            name='foto_produto2',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='allpost',
            name='foto_produto3',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='allpost',
            name='foto_produto4',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='allpost',
            name='foto_produto5',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
